---

- name: install python dependency
  gather_facts: no
  hosts: all
  tasks:
    - name: install python2
      raw: apt install -y python

- name: basic configuration
  hosts: all
  roles:
    - common
    - hostname
    - motd
    - geerlingguy.ntp
